### ISSUE TITLE
names of different actions?

### ISSUE THREAD

**Issue by asrjy** [mechyai/RL-EmsPy#7]
Hi @mechyai, I'm trying to replicate some papers that use different target setpoints. 

https://github.com/mechyai/RL-EmsPy/blob/01984a9bc37f35991073e17cf715687896d6ea8d/example_usage/simple_emspy_control.py#L96-L107

For example, a paper controls the supply air set point temperature of a VRF system. Where can I find the relevant actuators to do this?

**Comment by agl71** [comment]
Hi @mechyai,
I run simple_emspy_control.py in a python 3.8 env, but FileNotFoundError error happened.
Could you tell me how to slove it. The following is error message.

D:\EnergyPlusV9-6-0\EnergyPlusAPI.dll
Traceback (most recent call last):
  File "D:/workspace/RL-EmsPy-main/example_usage/simple_emspy_control.py", line 120, in <module>
    sim = BcaEnv(
  File "D:\workspace\RL-EmsPy-main\emspy\bca.py", line 29, in __init__
    super().__init__(ep_path, ep_idf_to_run, timesteps, tc_vars, tc_intvars, tc_meters, tc_actuator, tc_weather)
  File "D:\workspace\RL-EmsPy-main\emspy\emspy.py", line 98, in __init__
    self.api = EnergyPlusAPI()  # instantiation of Python EMS API
  File "D:\EnergyPlusV9-6-0\pyenergyplus\api.py", line 127, in __init__
    self.api = cdll.LoadLibrary(api_path())
  File "D:\Users\Administrator\anaconda3\envs\bao\lib\ctypes\__init__.py", line 453, in LoadLibrary
    return self._dlltype(name)
  File "D:\Users\Administrator\anaconda3\envs\bao\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\EnergyPlusV9-6-0\EnergyPlusAPI.dll' (or one of its dependencies). Try using the full path with constructor syntax.

Process finished with exit code 1

**Comment by mechyai** [comment]
Apologies for the late reply, unfortunately I am far removed from this project.
Knowing which actuator parameters to use requires deep understanding of the building model and IDF file you are using - I remember this being a very challenging part of the project, you should be familiar with EnergyPlus and can use OpenStudio to help understand the HVAC system and lookup the actuator names/parameters
